config/routes.rb
EmailMarketingSystem::Application.routes.draw do
  resources :emails, :prospects, :deliveries, :industries
  
  root to: "emails#index"
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :email_id, :prospect_id, :token
  
  belongs_to :email
  belongs_to :prospect
  
  def self.search(search)
    if search
      joins(:email, :prospect).where('emails.name LIKE :search OR prospects.company_name LIKE :search', search: "%#{search}%")
    else
      scoped
    end
  end
  
  def compile_body
    self.variables.each{|key, value| self.email.body.gsub!(key, value)}
    self.email.body
  end
  
  def variables
    defaults = {"%%CONTACT_NAME%%" => self.prospect.contact_name, 
                "%%COMPANY_NAME%%" => self.prospect.company_name, 
                "%%INDUSTRY_NAME%%" => self.prospect.industry.name, 
                "%%COMPANY_WEBSITE%%" => self.prospect.website}
    self.email.email_variables.each do |ev|
      defaults["%%#{ev.identifier}"] = ev.content
    end
    defaults
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :body, :description, :name, :subject, :email_variables_attributes
  
  has_many :email_variables
  has_many :deliveries
  
  accepts_nested_attributes_for :email_variables, :allow_destroy => true, :reject_if => proc { |attributes| attributes['identifier'].blank? }

end

app/models/email_variable.rb
class EmailVariable < ActiveRecord::Base
  attr_accessible :content, :email_id, :identifier
  
  belongs_to :email
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  attr_accessible :name, :practitioners
  
  has_many :prospects
end

app/models/prospect.rb
require 'csv'  

class Prospect < ActiveRecord::Base
  attr_accessible :address, :company_name, :contact_name, :email, :industry_id, :reference_url, :website
  
  belongs_to :industry
  has_many :deliveries
  
  def self.upload(file)
    count = 0
    CSV.parse(file.read, headers: true) do |row|
      row = row.to_hash
      if !row["email"].blank?
        row["industry_id"] = Industry.where(name: row["industry_id"]).first_or_create.id
        prospect = new(row)
        count += 1 if prospect.save
      end
    end
    count
  end
  
  def self.search(search)
    if search
      joins(:industry).where('company_name LIKE :search OR address LIKE :search OR industries.name LIKE :search', search: "%#{search}%")
    else
      scoped
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
    
    def sort_direction  
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"  
    end 
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  respond_to :html, :xml, :json
  helper_method :sort_direction, :sort_column

  def index
    @deliveries = Delivery.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(per_page: 100, page: params[:page])
  end
  
  def show
    @delivery = Delivery.find(params[:id])
  end
  
  def new
    @delivery = Delivery.new
  end
  
  def create
    email = params[:email]
    prospects = params[:prospect].delete_if {|k,v| v == "0"}
    prospects.each do |prospect|
      delivery = Delivery.create(prospect_id: prospect[0], email_id: email[0])
      DeliveryMailer.dynamic_email(delivery.compile_body, delivery.email.subject, delivery.prospect.email).deliver
    end 
    redirect_to deliveries_path
  end
   
  def edit
    @delivery = Delivery.find(params[:id])
  end
  
  def update
    @delivery = Delivery.find(params[:id])
    if @delivery.update_attributes(params[:delivery])  
      flash[:notice] = "Successfully updated delivery."  
    end  
    respond_with(@delivery, location: deliveries_path) 
  end
  
  def destroy
    @delivery = Delivery.find(params[:id])
    @delivery.destroy  
    flash[:notice] = "Successfully destroyed delivery."  
    respond_with(@delivery, location: deliveries_path)
  end
  
  private
    
    def sort_column  
      Delivery.column_names.include?(params[:sort]) ? params[:sort] : "prospect_id"  
    end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  respond_to :html, :xml, :json
  
  def index
    @emails = Email.all
  end
  
  def new
    @email = Email.new
  end
  
  def create
    @email = Email.new(params[:email])
    if @email.save 
      flash[:notice] = "Successfully created email."  
    end  
    respond_with(@email, location: edit_email_path(@email)) 
  end
  
  def edit
    @email = Email.find(params[:id])
  end
  
  def update
    @email = Email.find(params[:id])  
    if @email.update_attributes(params[:email])  
      flash[:notice] = "Successfully updated email."  
    end  
    respond_with(@email, location: edit_email_path(@email)) 
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @industry = Industry.new
    @industries = Industry.all
  end
  
  def show
    @industry = Industry.find(params[:id])
  end
  
  def new
    @industry = Industry.new
  end
  
  def create
    @industry = Industry.new(params[:industry])
    if @industry.save 
      flash[:notice] = "Successfully created industry."  
    end  
    respond_with(@industry, location: industries_path) 
  end
   
  def edit
    @industry = Industry.find(params[:id])
  end
  
  def update
    @industry = Industry.find(params[:id])
    if @industry.update_attributes(params[:industry])  
      flash[:notice] = "Successfully updated industry."  
    end  
    respond_with(@industry, location: industries_path) 
  end
  
  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy  
    flash[:notice] = "Successfully destroyed industry."  
    respond_with(@industry, location: industries_path)
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  respond_to :html, :xml, :json
  helper_method :sort_direction, :sort_column

  def index
    @prospects = Prospect.joins(:industry).search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(per_page: 50, page: params[:page])
  end
  
  def show
    @prospect = Prospect.find(params[:id])
  end
  
  def new
    @prospect = Prospect.new
  end
  
  def create
    if params[:prospect]
      @prospect = Prospect.create(params[:prospect])
    elsif params[:file]
      created = Prospect.upload(params[:file]) 
      flash[:notice] = "#{created} prospects were uploaded." 
    end
    respond_with(@prospect, location: prospects_path) 
  end
   
  def edit
    @prospect = Prospect.find(params[:id])
  end
  
  def update
    @prospect = Prospect.find(params[:id])
    if @prospect.update_attributes(params[:prospect])  
      flash[:notice] = "Successfully updated prospect."  
    end  
    respond_with(@prospect, location: prospects_path) 
  end
  
  def destroy
    @prospect = Prospect.find(params[:id])
    @prospect.destroy  
    flash[:notice] = "Successfully destroyed prospect."  
    respond_with(@prospect, location: prospects_path)
  end
  
  private
    
    def sort_column
      if params[:sort] == "industries.name" 
        params[:sort]
      elsif Prospect.column_names.include?(params[:sort])
        params[:sort]
      else
        "company_name"
      end
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    base_title = "Email Marketing System" 
    content_for(:title) { "#{page_title} | #{base_title}" }
    content_for(:heading) { page_title }
  end
  
  def sortable(column, title = nil)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{set_class(sort_direction)}" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}  
  end
  
  private
    
    def set_class(direction)
      sort_direction == "asc" ? "icon-arrow-up" : "icon-arrow-down" 
    end
end

app/views/deliveries/_form.html.erb
<h1><%= yield :heading %></h1>

<%= form_for @delivery do |f| %>
  <div class="row">
    <div class="well span6">
      <%= f.label :prospect_id, "Prospect" %>
      <%= f.collection_select :prospect_id, Prospect.order("company_name").all, :id, :company_name, {}, { class: "span6" } %>
      <%= f.label :email_id, "Email" %>
      <%= f.collection_select :email_id, Email.order("name").all, :id, :name, {}, { class: "span6" } %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to "Cancel", prospects_path, class: "btn"%>
    <%= f.submit "Send", class: "btn btn-primary"%>
  </div>
  
<% end %>

app/views/deliveries/index.html.erb
<% title "Deliveries" %>

<%= link_to "New delivery", new_delivery_path, class: "btn btn-success pull-right"%>
<h1><%= yield :heading %></h1>
<%= form_tag deliveries_path, method: 'get', class: "form-search pull-right" do %>
    <%= text_field_tag :search, params[:search], class: "input-medium" %>
    <%= submit_tag "Search", class: "btn" %>
<% end %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th><%= sortable "email.name", "Email" %></th>
      <th><%= sortable "prospect.company_name", "Prospect" %></th>
      <th><%= sortable "created_at", "Sent at" %></th>
    </tr>
  </thead>
  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.email.name %></td>
        <td><%= delivery.prospect._company_name %></td>
        <td><%= delivery.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @prospects %>

app/views/deliveries/new.html.erb
<% title "New Prospect" %>

<%= render "form" %>

app/views/industries/_form.html.erb
<%= form_for @industry do |f| %>
  <%= f.text_field :name, placeholder: "Industry" %>
  <%= f.text_field :practitioners, placeholder: "Practitioners" %>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/industries/edit.html.erb
<% title "Edit #{@industry.name}" %>

<h1><%= yield :heading %></h1>
<%= render "form" %>

app/views/industries/index.html.erb
<% title "Industries" %>

<h1><%= yield :heading %></h1>
<%= render "form" %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Practitioners</th>
    </tr>
  </thead>
  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= link_to industry.name, edit_industry_path(industry) %></td>
        <td><%= industry.practitioners %></td>
        <td><%= link_to "Delete", industry, class: "btn btn-small btn-danger pull-right", method: :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Email Marketing System", root_path, class: "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to "Emails", emails_path %></li>
              <li><%= link_to "Prospects", prospects_path %></li>
              <li><%= link_to "Industries", industries_path %></li>
              <li><%= link_to "Deliveries", new_delivery_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/header" %>
    
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">x</a>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/prospects/_form.html.erb
<h1><%= yield :heading %></h1>

<%= form_for @prospect do |f| %>
  <div class="row">
    <div class="well span6">
      <%= f.label :company_name, "Company" %>
      <%= f.text_field :company_name, class: "span6" %>
      <%= f.label :industry_id, "Industry" %>
      <%= f.collection_select :industry_id, Industry.order("name").all, :id, :name, class: "span6" %>
      <%= f.label :contact_name, "Contact" %>
      <%= f.text_field :contact_name, class: "span6" %>
      <%= f.label :address %>
      <%= f.text_field :address, class: "span6" %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "span6" %>
      <%= f.label :website %>
      <%= f.text_field :website, class: "span6" %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to "Cancel", prospects_path, class: "btn"%>
    <%= f.submit "Save", class: "btn btn-primary"%>
  </div>
  
<% end %>

app/views/prospects/_upload_form.html.erb
<%= form_tag prospects_path, method: :post, multipart: true, class: "pull-left" do |f| %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload", class: "btn btn-success" %>
<% end %>

app/views/prospects/edit.html.erb
<% title "Prospect #{@prospect.company_name}" %>

<%= render "form" %>

app/views/prospects/index.html.erb
<% title "Prospects" %>

<%= link_to "Add prospect", new_prospect_path, class: "btn btn-success pull-right"%>
<h1><%= yield :heading %></h1>
<%= render "upload_form" %>
<%= form_tag prospects_path, method: 'get', class: "form-search pull-right" do %>
    <%= text_field_tag :search, params[:search], class: "input-medium" %>
    <%= submit_tag "Search", class: "btn" %>
<% end %>

<%= form_tag deliveries_path do %>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th></th>
      <th><%= sortable "company_name", "Company" %></th>
      <th><%= sortable "industries.name", "Industry" %></th>
      <th><%= sortable "contact_name", "Contact" %></th>
      <th><%= sortable "address" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "website" %></th>
      <th>Emails sent</th>
    </tr>
  </thead>
  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= check_box "prospect", prospect.id %>
        <td><%= link_to prospect.company_name, edit_prospect_path(prospect) %></td>
        <td><%= prospect.industry.name %></td>
        <td><%= prospect.contact_name if prospect.contact_name %></td>
        <td><%= prospect.address if prospect.address %></td>
        <td><%= prospect.email if prospect.email %></td>
        <td><%= prospect.website if prospect.website %></td>
        <td><%= "YES" if prospect.deliveries.size > 0 %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @prospects %>
   <%= select_tag "email", options_from_collection_for_select(Email.order("name").all, "id", "name") %>
   <%= submit_tag "Send to selected", class: "btn btn-success" %>
<% end %>

app/views/prospects/new.html.erb
<% title "New Prospect" %>

<%= render "form" %>